# Suicide rate of countries per year (2000 - 2019)

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns

# TUTTI

In [21]:
# path Salvo
df_all_raw=pd.read_csv("C:/Users/Lavoro/Desktop/Data/Suicide rate of countries per year/suiciderateall.csv")
df_all=df_all_raw.copy()

In [2]:
# path Giovanni
df_all_raw=pd.read_csv(r"C:\Users\giova\Desktop\Boolean\Files\Slide\Modulo 6 - Final Project & Career Service\Suicide Rate of Countries per Year/suiciderateall.csv")
df_all=df_all_raw.copy()
df_all

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistanâ€¯*,7.7,7.9,7.9,7.7,7.8,7.6,7.6,7.4,7.2,...,6.7,6.4,6.2,6.2,6.0,6.0,6.0,6.0,5.9,6.0
1,Albania,5.2,4.7,4.8,4.9,4.9,7.7,7.8,8.1,8.1,...,7.6,7.6,4.8,4.8,4.5,4.2,4.2,4.1,3.9,3.7
2,Algeria,4.7,4.6,4.4,4.1,4.0,3.8,3.7,3.5,3.3,...,3.0,2.9,2.9,2.9,2.8,2.7,2.6,2.5,2.6,2.6
3,Angola,17.6,17.5,17.2,17.5,17.2,16.3,17.1,15.0,15.3,...,14.2,13.5,14.2,14.2,13.1,13.3,12.9,12.4,12.4,12.6
4,Antigua and Barbuda,2.0,1.9,1.3,1.4,2.0,1.3,0.4,0.3,0.2,...,0.1,0.2,0.0,0.0,0.4,0.4,0.5,0.0,0.3,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Venezuela,6.4,6.5,6.2,5.6,5.1,4.8,4.3,4.0,3.7,...,3.6,3.8,3.4,2.6,2.3,2.4,2.3,2.2,2.2,2.1
179,Vietnam,7.2,7.1,7.0,7.0,7.0,6.9,7.0,7.2,7.4,...,7.3,7.4,7.5,7.5,7.6,7.6,7.6,7.5,7.4,7.2
180,Yemen,8.5,8.4,8.2,8.1,8.1,8.0,7.8,7.7,7.8,...,7.4,7.2,7.2,7.1,7.0,6.8,7.0,6.9,7.1,7.1
181,Zambia,24.0,22.7,22.3,21.5,22.5,22.1,21.8,19.8,19.0,...,19.7,19.8,18.5,17.9,17.7,17.3,16.7,16.7,15.9,14.4
182,Zimbabwe,20.0,19.5,20.3,20.2,21.5,22.0,22.0,27.2,31.7,...,35.0,34.3,33.1,31.4,30.8,30.7,28.7,25.9,23.9,23.6

In [3]:
# ciclo per eliminare gli asterischi finali dalla colonna Country
for i in range(len(df_all['Country'])):
    if df_all['Country'][i].endswith('*'):
        df_all['Country'][i] = df_all['Country'][i][:-1]

C:\Users\giova\AppData\Local\Temp\ipykernel_4776\1834229016.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all['Country'][i] = df_all['Country'][i][:-1]

In [4]:
df_all

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistan,7.7,7.9,7.9,7.7,7.8,7.6,7.6,7.4,7.2,...,6.7,6.4,6.2,6.2,6.0,6.0,6.0,6.0,5.9,6.0
1,Albania,5.2,4.7,4.8,4.9,4.9,7.7,7.8,8.1,8.1,...,7.6,7.6,4.8,4.8,4.5,4.2,4.2,4.1,3.9,3.7
2,Algeria,4.7,4.6,4.4,4.1,4.0,3.8,3.7,3.5,3.3,...,3.0,2.9,2.9,2.9,2.8,2.7,2.6,2.5,2.6,2.6
3,Angola,17.6,17.5,17.2,17.5,17.2,16.3,17.1,15.0,15.3,...,14.2,13.5,14.2,14.2,13.1,13.3,12.9,12.4,12.4,12.6
4,Antigua and Barbuda,2.0,1.9,1.3,1.4,2.0,1.3,0.4,0.3,0.2,...,0.1,0.2,0.0,0.0,0.4,0.4,0.5,0.0,0.3,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Venezuela,6.4,6.5,6.2,5.6,5.1,4.8,4.3,4.0,3.7,...,3.6,3.8,3.4,2.6,2.3,2.4,2.3,2.2,2.2,2.1
179,Vietnam,7.2,7.1,7.0,7.0,7.0,6.9,7.0,7.2,7.4,...,7.3,7.4,7.5,7.5,7.6,7.6,7.6,7.5,7.4,7.2
180,Yemen,8.5,8.4,8.2,8.1,8.1,8.0,7.8,7.7,7.8,...,7.4,7.2,7.2,7.1,7.0,6.8,7.0,6.9,7.1,7.1
181,Zambia,24.0,22.7,22.3,21.5,22.5,22.1,21.8,19.8,19.0,...,19.7,19.8,18.5,17.9,17.7,17.3,16.7,16.7,15.9,14.4
182,Zimbabwe,20.0,19.5,20.3,20.2,21.5,22.0,22.0,27.2,31.7,...,35.0,34.3,33.1,31.4,30.8,30.7,28.7,25.9,23.9,23.6

# SOLO FEMMINE

In [19]:
# path Salvo
df_female_raw=pd.read_csv("C:/Users/Lavoro/Desktop/Data/Suicide rate of countries per year/suicideratefemale.csv")
df_female=df_female_raw.copy()

In [5]:
# path Giovanni
df_female_raw=pd.read_csv(r"C:\Users\giova\Desktop\Boolean\Files\Slide\Modulo 6 - Final Project & Career Service\Suicide Rate of Countries per Year/suicideratefemale.csv")
df_female=df_female_raw.copy()
df_female

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistanâ€¯*,7.8,7.9,7.7,7.6,7.6,7.4,7.3,7.1,6.9,...,6.4,6.2,6.1,6.0,5.9,5.8,5.8,5.5,5.6,5.7
1,Albania,2.9,3.0,3.0,3.2,3.1,5.2,5.7,5.7,5.8,...,5.9,8.2,3.2,3.2,2.9,2.8,2.7,2.5,2.4,2.2
2,Algeria,3.5,3.4,3.3,3.1,2.9,2.8,2.7,2.5,2.4,...,2.2,2.1,2.1,2.1,2.0,2.0,1.9,1.9,1.9,1.9
3,Angola,6.2,6.1,6.5,6.9,6.8,6.5,6.8,5.9,6.1,...,5.6,5.2,5.4,5.2,4.8,5.1,5.1,4.9,4.6,4.7
4,Antigua and Barbuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.8,0.8,0.9,0.0,0.6,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Venezuela,1.7,1.8,1.9,1.8,1.6,1.5,1.3,1.3,1.1,...,1.1,0.9,1.0,0.8,0.7,0.8,0.8,0.8,0.7,0.7
179,Vietnam,5.2,5.0,4.9,4.8,4.7,4.6,4.5,4.5,4.4,...,4.2,4.2,4.2,4.2,4.3,4.2,4.2,4.2,4.2,4.2
180,Yemen,6.5,6.5,6.2,6.1,6.2,6.0,5.9,5.8,5.9,...,5.5,5.4,5.5,5.4,5.2,5.0,5.1,5.1,5.3,5.3
181,Zambia,14.5,13.4,12.6,11.4,11.9,11.4,11.0,9.2,8.2,...,9.2,9.2,8.7,8.5,7.9,7.1,6.7,6.6,6.0,5.3
182,Zimbabwe,14.2,13.0,13.5,13.7,15.7,15.2,18.2,21.8,25.5,...,23.9,21.8,20.9,21.3,21.1,19.2,17.7,15.0,13.5,13.5

In [6]:
# ciclo per eliminare gli asterischi finali dalla colonna Country
for i in range(len(df_female['Country'])):
    if df_female['Country'][i].endswith('*'):
        df_female['Country'][i] = df_female['Country'][i][:-1]

C:\Users\giova\AppData\Local\Temp\ipykernel_4776\2170712638.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_female['Country'][i] = df_female['Country'][i][:-1]

In [7]:
df_female

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistan,7.8,7.9,7.7,7.6,7.6,7.4,7.3,7.1,6.9,...,6.4,6.2,6.1,6.0,5.9,5.8,5.8,5.5,5.6,5.7
1,Albania,2.9,3.0,3.0,3.2,3.1,5.2,5.7,5.7,5.8,...,5.9,8.2,3.2,3.2,2.9,2.8,2.7,2.5,2.4,2.2
2,Algeria,3.5,3.4,3.3,3.1,2.9,2.8,2.7,2.5,2.4,...,2.2,2.1,2.1,2.1,2.0,2.0,1.9,1.9,1.9,1.9
3,Angola,6.2,6.1,6.5,6.9,6.8,6.5,6.8,5.9,6.1,...,5.6,5.2,5.4,5.2,4.8,5.1,5.1,4.9,4.6,4.7
4,Antigua and Barbuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.0,0.0,0.8,0.8,0.9,0.0,0.6,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Venezuela,1.7,1.8,1.9,1.8,1.6,1.5,1.3,1.3,1.1,...,1.1,0.9,1.0,0.8,0.7,0.8,0.8,0.8,0.7,0.7
179,Vietnam,5.2,5.0,4.9,4.8,4.7,4.6,4.5,4.5,4.4,...,4.2,4.2,4.2,4.2,4.3,4.2,4.2,4.2,4.2,4.2
180,Yemen,6.5,6.5,6.2,6.1,6.2,6.0,5.9,5.8,5.9,...,5.5,5.4,5.5,5.4,5.2,5.0,5.1,5.1,5.3,5.3
181,Zambia,14.5,13.4,12.6,11.4,11.9,11.4,11.0,9.2,8.2,...,9.2,9.2,8.7,8.5,7.9,7.1,6.7,6.6,6.0,5.3
182,Zimbabwe,14.2,13.0,13.5,13.7,15.7,15.2,18.2,21.8,25.5,...,23.9,21.8,20.9,21.3,21.1,19.2,17.7,15.0,13.5,13.5

# SOLO MASCHI

In [18]:
# path Salvo
df_male_raw=pd.read_csv("C:/Users/Lavoro/Desktop/Data/Suicide rate of countries per year/suicideratemale.csv")
df_male=df_male_raw.copy()

In [8]:
# path Giovanni
df_male_raw=pd.read_csv(r"C:\Users\giova\Desktop\Boolean\Files\Slide\Modulo 6 - Final Project & Career Service\Suicide Rate of Countries per Year/suicideratemale.csv")
df_male=df_male_raw.copy()
df_male

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistanâ€¯*,7.6,7.9,8.0,7.8,7.9,7.8,7.8,7.7,7.4,...,6.9,6.6,6.4,6.3,6.1,6.1,6.2,6.3,6.2,6.2
1,Albania,7.6,6.5,6.6,6.6,6.7,10.2,10.1,10.5,10.5,...,9.5,7.3,6.6,6.5,6.2,5.7,5.7,5.7,5.6,5.3
2,Algeria,5.9,5.7,5.6,5.2,5.0,4.8,4.6,4.4,4.2,...,3.8,3.7,3.7,3.6,3.5,3.4,3.3,3.2,3.2,3.3
3,Angola,30.0,29.8,29.0,29.1,28.6,27.1,28.4,25.2,25.5,...,23.9,22.8,24.1,24.3,22.6,22.7,21.8,21.0,21.3,21.7
4,Antigua and Barbuda,4.5,4.2,2.8,3.2,4.3,2.9,0.9,0.7,0.5,...,0.3,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Venezuela,11.3,11.5,10.7,9.7,8.7,8.3,7.5,7.0,6.5,...,6.3,6.9,6.0,4.5,4.0,4.1,3.9,3.9,3.9,3.7
179,Vietnam,9.4,9.5,9.3,9.4,9.6,9.6,9.9,10.3,10.6,...,10.7,10.9,11.1,11.1,11.3,11.3,11.2,11.1,10.8,10.6
180,Yemen,10.5,10.4,10.2,10.1,10.2,10.0,9.8,9.8,9.8,...,9.3,9.1,9.1,9.0,9.0,8.7,9.0,8.7,9.0,9.0
181,Zambia,35.9,34.3,34.5,34.2,35.8,35.8,35.6,33.4,32.8,...,33.3,33.4,31.1,30.0,30.2,30.0,29.1,29.1,28.1,25.7
182,Zimbabwe,28.2,28.6,29.8,29.4,30.1,32.1,28.5,36.3,42.0,...,51.6,52.4,50.7,46.4,45.3,47.4,44.5,41.3,38.6,37.8

In [9]:
# ciclo per eliminare gli asterischi finali dalla colonna Country
for i in range(len(df_male['Country'])):
    if df_male['Country'][i].endswith('*'):
        df_male['Country'][i] = df_male['Country'][i][:-1]

C:\Users\giova\AppData\Local\Temp\ipykernel_4776\1941039963.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_male['Country'][i] = df_male['Country'][i][:-1]

In [11]:
df_male

,Country,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistan,7.6,7.9,8.0,7.8,7.9,7.8,7.8,7.7,7.4,...,6.9,6.6,6.4,6.3,6.1,6.1,6.2,6.3,6.2,6.2
1,Albania,7.6,6.5,6.6,6.6,6.7,10.2,10.1,10.5,10.5,...,9.5,7.3,6.6,6.5,6.2,5.7,5.7,5.7,5.6,5.3
2,Algeria,5.9,5.7,5.6,5.2,5.0,4.8,4.6,4.4,4.2,...,3.8,3.7,3.7,3.6,3.5,3.4,3.3,3.2,3.2,3.3
3,Angola,30.0,29.8,29.0,29.1,28.6,27.1,28.4,25.2,25.5,...,23.9,22.8,24.1,24.3,22.6,22.7,21.8,21.0,21.3,21.7
4,Antigua and Barbuda,4.5,4.2,2.8,3.2,4.3,2.9,0.9,0.7,0.5,...,0.3,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,Venezuela,11.3,11.5,10.7,9.7,8.7,8.3,7.5,7.0,6.5,...,6.3,6.9,6.0,4.5,4.0,4.1,3.9,3.9,3.9,3.7
179,Vietnam,9.4,9.5,9.3,9.4,9.6,9.6,9.9,10.3,10.6,...,10.7,10.9,11.1,11.1,11.3,11.3,11.2,11.1,10.8,10.6
180,Yemen,10.5,10.4,10.2,10.1,10.2,10.0,9.8,9.8,9.8,...,9.3,9.1,9.1,9.0,9.0,8.7,9.0,8.7,9.0,9.0
181,Zambia,35.9,34.3,34.5,34.2,35.8,35.8,35.6,33.4,32.8,...,33.3,33.4,31.1,30.0,30.2,30.0,29.1,29.1,28.1,25.7
182,Zimbabwe,28.2,28.6,29.8,29.4,30.1,32.1,28.5,36.3,42.0,...,51.6,52.4,50.7,46.4,45.3,47.4,44.5,41.3,38.6,37.8

In [14]:
# niente valori NaN e datatype a posto di tutti e tre i file
df_female.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183 entries, 0 to 182
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  183 non-null    object
 1   2000     183 non-null    float64
 2   2001     183 non-null    float64
 3   2002     183 non-null    float64
 4   2003     183 non-null    float64
 5   2004     183 non-null    float64
 6   2005     183 non-null    float64
 7   2006     183 non-null    float64
 8   2007     183 non-null    float64
 9   2008     183 non-null    float64
 10  2009     183 non-null    float64
 11  2010     183 non-null    float64
 12  2011     183 non-null    float64
 13  2012     183 non-null    float64
 14  2013     183 non-null    float64
 15  2014     183 non-null    float64
 16  2015     183 non-null    float64
 17  2016     183 non-null    float64
 18  2017     183 non-null    float64
 19  2018     183 non-null    float64
 20  2019     183 non-null    float64
dtypes: float64(20), object(1)
memory usage: 30.1+ KB

In [15]:
# esportazione file Giovanni
df_all = df_all.to_excel(r'C:\Users\giova\Desktop\Github Final Project\Dataset puliti\suiciderateall.xlsx')

In [16]:
df_female = df_female.to_excel(r'C:\Users\giova\Desktop\Github Final Project\Dataset puliti\suicideratefemale.xlsx')

In [17]:
df_male = df_male.to_excel(r'C:\Users\giova\Desktop\Github Final Project\Dataset puliti\suicideratemale.xlsx')